
curl -X POST "https://samantaanalysis.uxlivinglab.online/api/v1/business-analysis/?type=business_info" \
     -H "Content-Type: application/json" \
     -d '{
           "google_link": "https://www.google.com/maps/place/Seematti/@9.9852108,76.2801247,17z/data=!3m1!4b1!4m6!3m5!1s0x3b0872b11939e187:0xdebcaecf7d5caa89!8m2!3d9.9852108!4d76.2826996!16s%2Fg%2F1tkslsyt!5m1!1e1?entry=ttu&g_ep=EgoyMDI1MDIyNi4xIKXMDSoJLDEwMjExNDU1SAFQAw%3D%3D",
           "website": "https://example.com"
         }'

###

curl -X POST "https://samantaanalysis.uxlivinglab.online/api/v1/business-analysis/?type=sowt_analysis_report" \
     -H "Content-Type: application/json" \
     -d '{
          "email": "manish@dowellresearch.in",
          "occurrences": 1,
          "name": "Seematti",
          "address": "Old No 40/9805, New No 66, 4688, Mahatma Gandhi Rd, Kacheripady, Ernakulam, Kerala 682035",
          "url": "https://www.google.com/maps/place/Seematti/@9.9852108,76.2801247,17z/data=!3m1!4b1!4m6!3m5!1s0x3b0872b11939e187:0xdebcaecf7d5caa89!8m2!3d9.9852108!4d76.2826996!16s%2Fg%2F1tkslsyt!5m1!1e1?entry=ttu&g_ep=EgoyMDI1MDIyNi4xIKXMDSoJLDEwMjExNDU1SAFQAw%3D%3D",
          "phone": "0484 411 2233",
          "rating": 4.5,
          "reviews": 12,
          "plus_code": "X7PM+33 Ernakulam, Kerala",
          "website": "https://seematti.com/",
          "latitude": 9.9852108,
          "longitude":76.2826996
     }'

###
curl -X POST "https://100105.pythonanywhere.com/api/v3/experience_database_services/?type=register_user" \
     -H "Content-Type: application/json" \
     -d '{
           "product_number": "UXLIVINGLAB012",
           "email": "manish@dowellresearch.in"
         }'

###
curl -X GET "https://100105.pythonanywhere.com/api/v3/experience_database_services/?type=get_user_email&product_number=UXLIVINGLAB010&email=lucifer25gaming@gmail.com"

###
curl -X POST "https://100085.pythonanywhere.com/api/email/" \
     -H "Content-Type: application/json" \
     -d '{
           "toname": "Recipient Name",
           "toemail": "recipient@example.com",
           "subject": "Your Email Subject",
           "email_content": "Hello, this is a test email message."
         }'

###
curl -X POST "http://127.0.0.1:8000/v1/business-analysis/?type=linkedin_analysis_report" \
     -H "Content-Type: application/json" \
     -d '{
          "email": "manish@dowellresearch.in",
          "occurrences": 1,
          "linkedin_link":"https://www.linkedin.com/in/hiroyuki-sasaki-657b1319b/"
     }'


###

curl -X POST "https://samantaanalysis.uxlivinglab.online/api/v1/business-analysis/?type=google_review_analysis_report" \
     -H "Content-Type: application/json" \
     -d '{
          "email": "manish@dowellresearch.in",
          "occurrences": 1,
          "name": "Seematti",
          "address": "Old No 40/9805, New No 66, 4688, Mahatma Gandhi Rd, Kacheripady, Ernakulam, Kerala 682035",
          "url": "https://www.google.com/maps/place/Seematti/@9.9852108,76.2801247,17z/data=!3m1!4b1!4m6!3m5!1s0x3b0872b11939e187:0xdebcaecf7d5caa89!8m2!3d9.9852108!4d76.2826996!16s%2Fg%2F1tkslsyt!5m1!1e1?entry=ttu&g_ep=EgoyMDI1MDIyNi4xIKXMDSoJLDEwMjExNDU1SAFQAw%3D%3D",
          "phone": "0484 411 2233",
          "rating": 4.5,
          "reviews": 12,
          "plus_code": "X7PM+33 Ernakulam, Kerala",
          "website": "https://seematti.com/",
          "latitude": 9.9852108,
          "longitude":76.2826996
     }'



