version: '3.9'
services:

  client:
    build: ./client
    container_name: client_container
    ports:
      - '5173:5173'
    restart: always
    env_file: 
      - ./.env
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - queue-net
    depends_on:
      - server

  server:
    build: ./server
    container_name: server_container
    ports:
      - '8000:8000'
    volumes:
      - ./server:/usr/src/app
    restart: always
    env_file: 
      - ./.env
    networks:
      - queue-net

  # nginx:
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   container_name: nginx
  #   ports:
  #     - '80:80'
  #     - '443:443'
  #   volumes:
  #     - ./nginx:/usr/src/app
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #     - /etc/letsencrypt/live/www.scales.uxlivinglab.online/fullchain.pem:/etc/letsencrypt/live/www.scales.uxlivinglab.online/fullchain.pem:ro
  #     - /etc/letsencrypt/live/www.scales.uxlivinglab.online/privkey.pem:/etc/letsencrypt/live/www.scales.uxlivinglab.online/privkey.pem:ro
  #   restart: always
  #   networks:
  #     - queue-net
  #   depends_on:
  #     - backend
  #     - frontend

networks:
  queue-net:
    driver: bridge

volumes:
  mongo-data:
  cache: